import home from './home';
import submission from './submission';
import atom from './atom';
import grids from './grids';
import notice from './notice';
import article_status from './article_status';
import payment from './payment';
import contact from './contact';
import cooperation from './cooperation';
